#!/bin/sh

case "$ACTION" in
        ifup)
                if [ "$INTERFACE" = "wan6" ]; then
                        ip -6 route add `ip -6 route show default | sed -n -e 's/default from //' -e 's/ via .*$//g' -e '/64$/p'` dev br-lan metric 128
                        logger -t IPV6 "Route resetting for $INTERFACE up"
                fi
                ;;
esac
